const STRIPE_SIMPLE_DONATION = [
    'price_1O9RTzH1rXnXzXAphCRUIvcG',
    'price_1O9RUwH1rXnXzXApwrCJAIlE',
    'price_1O9RVTH1rXnXzXAporGfcIj6',
    'price_1O9RbOH1rXnXzXAplKfGiMX0',
]

const STRIPE_RECURRING_DONATION = [
    'price_1O9RWMH1rXnXzXAp9VgPohde',
    'price_1O9RWkH1rXnXzXApmqQP1N4A',
    'price_1O9RX3H1rXnXzXApz8AK5rua',
    'price_1O9RbmH1rXnXzXApnUPnweef',
]

const STRIPE_GHIOZDANOK_DONATION = 'price_1O9RYBH1rXnXzXAp7KsUAxwU'
const STRIPE_VEDEREDECRACIUN_DONATION = 'price_1O9RYwH1rXnXzXApzQEF28hQ'
const STRIPE_CATRAFUSALE_DONATION = 'price_1O9RZVH1rXnXzXApWUMewYST'
const STRIPE_HEALTHYVISION_DONATION = 'price_1O9RaOH1rXnXzXAp9f9UtTsc'

const MIND_MATTERS_MINDACCESS = 'price_1OyfwSH1rXnXzXApCbHQYRpq'
const MIND_MATTERS_MINDFUEL = 'price_1OyfxoH1rXnXzXAptsqOPQCq'

enum CATRAFUSALE_PACKAGES {
    SINGLE = 'price_1O8OR1H1rXnXzXAphxmN3uIh',
    DOUBLE = 'price_1O8OR1H1rXnXzXAphxmN3uIh',
    SINGLE_TABLE = 'price_1O8OR1H1rXnXzXAphxmN3uIh',
    MIXT = 'price_1O8OR1H1rXnXzXAphxmN3uIh',
}

export {
    STRIPE_SIMPLE_DONATION,
    STRIPE_RECURRING_DONATION,
    STRIPE_GHIOZDANOK_DONATION,
    STRIPE_VEDEREDECRACIUN_DONATION,
    STRIPE_CATRAFUSALE_DONATION,
    STRIPE_HEALTHYVISION_DONATION,
    MIND_MATTERS_MINDACCESS,
    MIND_MATTERS_MINDFUEL,
    CATRAFUSALE_PACKAGES,
}
